### ISSUE TITLE
InputTextIntl: initialValue should be localized 

### ISSUE THREAD

**Issue by masmau** [melfore/mosaic#90]

**Comment by luciobordonaro** [comment]
I have encountered this as well when working with complex components like `Table` and `Modal`, we should find a way to localize several props at the same time.
For this reason I think we should consider to rewrite the `withIntl` HOC component and rethink its logic.

I won't say that it has a high priority because host projects can localize values and set them into Mosaic components, but definitively it has _some priority_.

Since we are starting to collect different issues on `withIntl` HOC, I'm also creating a issue that collects all related issues, because the idea would be to solve them all in one PR.

**Comment by luciobordonaro** [comment]
This can be closed with release of v1.1.x

It is not possible to localize automatically the value of a Input, the reason is that it is not a static text (as labels or others).
Value of the input is subject to changes over time, and this would require to have potentially infinite translations available.
What the user can do is to pass-in as `initialValue` something that is already localized on utilizing project.
